katrina/foodsupply/urls.py
from django.conf.urls import url
from . import views
app_name='foodsupply'

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^hub/$', views.hub, name='hub'),

    url(r'^household/$', views.household_main, name='household'),
    url(r'^view_household$', views.view_household, name='view_household'),
    url(r'^thankyou$', views.add_household, name='thankyou'),
    url(r'^report1$', views.report_1, name='report1'),
    url(r'^report2$', views.report_2, name='report2'),
    url(r'^report3$', views.report_3, name='report3'),
    url(r'^optimization$', views.optimization, name='optimization'),
]

katrina/katrina/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^foodsupply/', include('foodsupply.urls')),
    url(r'^admin/', admin.site.urls),
]

katrina/foodsupply/models.py
from django.db import models
from django.core.urlresolvers import reverse

class Hub(models.Model):
    hub_id = models.IntegerField(primary_key=True, default=0)
    population = models.IntegerField(default=0)
    current_storage = models.IntegerField(default=0)

    def _get_days_to_exhaustion():
        return round(self.current_storage/self.population,0)
    days_to_exhaustion = property(_get_days_to_exhaustion)
    def _get_priority_score():
       return round(self.population/self.current_storage*10,0)
    priority_score = property(_get_priority_score)

    def __str__(self):
        return("Hub ID: {hub_id}  ".format(hub_id=self.hub_id))

class household(models.Model):
    household_id = models.IntegerField(default=0)

    def _get_hub():
        if(self.household_id>0 and self.household_id<6):
            return()
        elif(self.household_id>5 and self.household_id<11):
            return(2)
        else:
            return(3)
    from_hub = property(_get_hub)
    house_population = models.IntegerField(default=0)

    def __str__(self):
        return("House ID: {household_id}  ".format(household_id=self.household_id))

katrina/foodsupply/forms.py
from django import forms
from django.forms import ModelForm
from .models import household

class householdForm(ModelForm):
    class Meta:
        model = household
        fields = "__all__"

katrina/foodsupply/views.py
from django.http import Http404
from django.http import HttpResponse
from django.shortcuts import render, get_object_or_404
import pandas as pd
import datetime
from .models import Hub, household
from django.views import generic
from .forms import householdForm
"""
class IndexView(generic.ListView):
    def __init__(self, arg):
        superIndexView, self).__init__()
        self.arg = arg

"""

def index(request):
    #all_albums = Album.objects.all()
    #context = {'all_albums': all_albums}
    return render(request, 'foodsupply/index.html')
    #return HttpResponse("Hello, world. You're at the foodsupply index.")

def household_main(request):
    return render(request, 'foodsupply/household.html')

def hub(request):
    """
    Excuse the really disgusting redundancy, it was 3:30AM, and I had run out of juice
    """
    household_df = pd.DataFrame(list(household.objects.all().values()))
    hub_1 = dict()
    hub_1['house_count']=0
    hub_1['population']=0

    hub_2 = dict()
    hub_2['house_count']=0
    hub_2['population']=0

    hub_3 = dict()
    hub_3['house_count']=0
    hub_3['population']=0

    for ele,house in household_df.iterrows():
        if(house['household_id']> 0 and house['household_id'] < 6):
            hub_1['house_count']+=1
            hub_1['population']+=int(house['house_population'])
        elif(house['household_id']> 5 and house['household_id'] < 11):
            hub_2['house_count']+=1
            hub_2['population']+=int(house['house_population'])
        else:
            hub_3['house_count']+=1
            hub_3['population']+=int(house['house_population'])
    print("PROBLEM 2!!!")
    hub_db_1 = Hub.objects.get(pk=1)
    hub_db_1.population = hub_1['population']
    hub_db_1.save()
    hub_db_2 = Hub.objects.get(pk=2)
    hub_db_2.population = hub_1['population']
    hub_db_2.save()
    hub_db_3 = Hub.objects.get(pk=3)
    hub_db_3.population = hub_1['population']
    hub_db_3.save()

    hub_1['days_to_exhaustion'] = round(hub_db_1.current_storage/hub_1['population'],0)
    hub_2['days_to_exhaustion'] = round(hub_db_2.current_storage/hub_2['population'],0)
    hub_3['days_to_exhaustion'] = round(hub_db_3.current_storage/hub_3['population'],0)

    hub_1['critical_score'] = round(1/hub_1['days_to_exhaustion']*hub_1['population']/2,0)
    hub_2['critical_score'] = round(1/hub_2['days_to_exhaustion']*hub_2['population']/2,0)
    hub_3['critical_score'] = round(1/hub_3['days_to_exhaustion']*hub_3['population']/2,0)

    context = {'hub_1':hub_1, 'hub_2':hub_2, 'hub_3':hub_3}
    return render(request, 'foodsupply/hub.html',context)

def add_household(request):
    if request.method == 'POST':
        form = householdForm(request.POST)
        if form.is_valid():
            form.save()
    return render(request, 'foodsupply/thankyou.html')

def view_household(request):
    df = pd.DataFrame(list(Hub.objects.all().values()))
    all_hub = Hub.objects.all()
    context = {'all_hub': all_hub}
    return render(request, 'foodsupply/view_household.html', context)

def report_1(request):
    house_list = list(household.objects.all().values())
    hub_1_houses = []
    hub_1 = dict()
    hub_1['house_count']=0
    hub_1['population']=0
    for house in house_list:
        if(house['household_id']> 0 and house['household_id'] < 6):
            hub_1_houses.append(house)
            hub_1['house_count']+=1
            hub_1['population']+=int(house['house_population'])
    hub_db_1 = Hub.objects.get(pk=1)
    hub_1['days_to_exhaustion'] = round(hub_db_1.current_storage/hub_1['population'],0)
    hub_1['critical_score'] = round(1/hub_1['days_to_exhaustion']*hub_1['population']/2,0)
    context = {'hub_1_houses': hub_1_houses, 'hub_1': hub_1}
    return render(request, 'foodsupply/report_hub_1.html', context)

def report_2(request):
    house_list = list(household.objects.all().values())
    hub_2_houses = []
    hub_2 = dict()
    hub_2['house_count']=0
    hub_2['population']=0
    for house in house_list:
        if(house['household_id']> 5 and house['household_id'] < 11):
            hub_2_houses.append(house)
            hub_2['house_count']+=1
            hub_2['population']+=int(house['house_population'])
    hub_db_2 = Hub.objects.get(pk=1)
    hub_2['days_to_exhaustion'] = round(hub_db_2.current_storage/hub_2['population'],0)
    hub_2['critical_score'] = round(1/hub_2['days_to_exhaustion']*hub_2['population']/2,0)
    context = {'hub_2_houses': hub_2_houses, 'hub_2': hub_2}
    return render(request, 'foodsupply/report_hub_2.html', context)

def report_3(request):
    house_list = list(household.objects.all().values())
    hub_3_houses = []
    hub_3 = dict()
    hub_3['house_count']=0
    hub_3['population']=0
    for house in house_list:
        if(house['household_id']> 10):
            hub_3_houses.append(house)
            hub_3['house_count']+=1
            hub_3['population']+=int(house['house_population'])
    hub_db_3 = Hub.objects.get(pk=1)
    hub_3['days_to_exhaustion'] = round(hub_db_3.current_storage/hub_3['population'],0)
    hub_3['critical_score'] = round(1/hub_3['days_to_exhaustion']*hub_3['population']/2,0)
    context = {'hub_3_houses': hub_3_houses, 'hub_3': hub_3}
    return render(request, 'foodsupply/report_hub_3.html', context)

def optimization(request):
    hub_list = list(Hub.objects.all().values())
    hub_json_list=list()
    for hub in hub_list:
        #print(hub)
        hub_json = dict()
        hub_json['current_storage'] = hub['current_storage']
        hub_json['population'] = hub['population']
        hub_json['hub_id'] = hub['hub_id']
        hub_json['days_to_exhaust'] = round(hub['current_storage']/hub['population'],0)
        hub_json['critical_score'] = round(1/hub_json['days_to_exhaust']*hub['population']/2,0)
        #print(hub_json)
        hub_json_list.append(hub_json)
        hub_df = pd.DataFrame(hub_json_list)
    optimize = get_optimize(hub_df)
    context = {'optimize': optimize}
    print(context)
    return render(request, 'foodsupply/optimization.html', context)

def get_optimize(hub_df):
    critical_hub = hub_df.loc[hub_df['critical_score'].idxmax()]
    safe_hub = hub_df.loc[hub_df['critical_score'].idxmin()]
    move_quantity = round((safe_hub['current_storage']-critical_hub['current_storage'])/3,0)
    optimize = {'from_hub':safe_hub['hub_id'],
                'to_hub':critical_hub['hub_id'],
                'move_quantity': move_quantity}

    return(optimize)

"""
df = pd.DataFrame(list(BlogPost.objects.filter(date__gte=datetime.datetime(2012, 5, 1)).values()))

# limit which fields
df = pd.DataFrame(list(BlogPost.objects.all().values('author', 'date', 'slug')))
"""

katrina/foodsupply/templates/foodsupply/household.html
<!DOCTYPE html>
<html>
<style>
* {
    box-sizing: border-box;
}

  .navbar {
      margin-bottom: 0;
      border-radius: 0;
    }

    .navbar {
        font-family: Montserrat, sans-serif;
        margin-bottom: 0;
        background-color: #2d2d30;
        border: 0;
        font-size: 11px !important;
        letter-spacing: 4px;
        opacity: 0.9;
    }
    .navbar li a, .navbar .navbar-brand {
        color: #d5d5d5 !important;
    }
    .navbar-nav li a:hover {
        color: #fff !important;
    }
    .navbar-nav li.active a {
        color: #fff !important;
        background-color: #29292c !important;
    }
    .navbar-default .navbar-toggle {
        border-color: transparent;
    }
    .open .dropdown-toggle {
        color: #000;
        background-color: #555 !important;
    }
    .dropdown-menu li a {
        color: #000 !important;
    }
    .dropdown-menu li a:hover {
        background-color: red !important;
    }

.jumbotron {
        background-color: #89D3D6;
        color: #fff;
        padding: 100px 25px;
        background-image: url("../img/jumbotron_bg.jpg");
        background-size: cover;
    }



input[type=text], select, textarea{
    width: 100%;
    padding: 12px;
    border: 1px solid #ccc;
    border-radius: 4px;
    box-sizing: border-box;
    resize: vertical;
}

input:invalid+span:after {
  content: 'Value must be greater than or equal to 0.';
  padding-left: 5px;
}


.panel {
     border: 1px solid #A2ECD7;
     border-radius:0 !important;
     transition: box-shadow 0.5s;
 }
 .panel:hover {
     box-shadow: 15px 0px 40px rgba(0,0,0, .2);
 }

 .panel-heading {
     color: #fff !important;
     background-color: #A2ECD7 !important;
     padding: 25px;
     border-bottom: 0px solid transparent;
     border-top-left-radius: 0px;
     border-top-right-radius: 0px;
     border-bottom-left-radius: 0px;
     border-bottom-right-radius: 0px;
 }
 .panel-footer {
     background-color: white !important;
 }



label {
    padding: 12px 12px 12px 0;
    display: inline-block;
}


input[type=submit] {
    background-color: #0C666F;
    color: #EDEAE5;
    padding: 12px 20px;
    border: none;
    border-radius: 4px;
    cursor: pointer;
    float: right;
}

input[type=submit]:hover {
    background-color: #FFF8C9;
    color:#0C666F
}

.container {
    border-radius: 5px;
    background-color: #f2f2f2;
    padding: 20px;
}

.col-25 {
    float: left;
    width: 25%;
    margin-top: 6px;
}

.col-75 {
    float: left;
    width: 75%;
    margin-top: 6px;
}

/* Clear floats after the columns */
.row:after {
    content: "";
    display: table;
    clear: both;
}
footer {
    background-color: #2d2d30;
    color: #f5f5f5;
    padding: 32px;
    position: fixed;

left: 0;

right: 0;

bottom: 0;

}
footer a {
    color: #f5f5f5;
}
footer a:hover {
    color: #777;
    text-decoration: none;
}

/* Responsive layout - when the screen is less than 600px wide, make the two columns stack on top of each other instead of next to each other */
@media (max-width: 600px) {
    .col-25, .col-75, input[type=submit] {
        width: 100%;
        margin-top: 0;
    }
}
</style>
<head>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
</head>
<body>
<div class="CampUI">

    <nav class="navbar navbar-inverse">
      <div class="container-fluid">
        <div class="navbar-header">
          <div class="navbar-header">
            <a class="navbar-brand" href="{% url 'foodsupply:index' %}">K0</a>
          </div>
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
        </div>
        <div class="collapse navbar-collapse" id="myNavbar">
          <ul class="nav navbar-nav">
            <li><a href="{% url 'foodsupply:index' %}">Home</a></li>
          </ul>
          <ul class="nav navbar-nav navbar-right">
              <li class="dropdown"><a class="dropdown-toggle"  data-toggle="dropdown" href="#">Household<span class="caret"></span></a>
                <ul class="dropdown-menu">
                  <li><a href="{% url 'foodsupply:household' %}">Household</a></li>
                  <li><a href="{% url 'foodsupply:hub' %}">Hub Manager</a></li>
                </ul>
              </li>
          </ul>
        </div>
      </div>
    </nav>

    <div class="jumbotron text-center">
      <h1>Household</h1>
      <p>Request for Resources</p>
    </div>



<div id="role" class="container-fluid">
  <div class="row">

    <form action="{% url 'foodsupply:thankyou' %}" method="post"> {% csrf_token %}

      <div class="col-md-6 col-xs-12">
        <div class="panel panel-default text-center">
          <div class="panel-heading">
            <a style="text-decoration:none;color:white;">
                <h1>Household ID</h1>
            </a>
          </div>
          <div class="panel-footer">
            <input type="number" name="household_id" min="0" class="form-control" id="household_id" placeholder="Enter Household ID...">
            <span class="validity"></span>
          </div>
        </div>
      </div>
      <div class="col-md-6 col-xs-12">
        <div class="panel panel-default text-center">
          <div class="panel-heading">
            <a style="text-decoration:none;color:white;">
                <h1>Food Units</h1>
            </a>
          </div>
          <div class="panel-footer">
            <input type="number" name="house_population" min="0" class="form-control" id="house_population" placeholder="Enter Number of Food Units Required...">
            <span class="validity"></span>
          </div>
        </div>
      </div>
        <div class="col-md-12">
            <input action="{% url 'foodsupply:thankyou' %}" type="submit" class="btn btn-primary" value="Submit">
        </div>
    </form>
  </div>
</div>
<br>
<br>

</body>
</html>

katrina/foodsupply/templates/foodsupply/hub.html
<!DOCTYPE html>
<html>
<style>
* {
    box-sizing: border-box;
}

  .navbar {
      margin-bottom: 0;
      border-radius: 0;
    }
    .navbar {
        font-family: Montserrat, sans-serif;
        margin-bottom: 0;
        background-color: #2d2d30;
        border: 0;
        font-size: 11px !important;
        letter-spacing: 4px;
        opacity: 0.9;
    }
    .navbar li a, .navbar .navbar-brand {
        color: #d5d5d5 !important;
    }
    .navbar-nav li a:hover {
        color: #fff !important;
    }
    .navbar-nav li.active a {
        color: #fff !important;
        background-color: #29292c !important;
    }
    .navbar-default .navbar-toggle {
        border-color: transparent;
    }
    .open .dropdown-toggle {
        color: #000;
        background-color: #555 !important;
    }
    .dropdown-menu li a {
        color: #000 !important;
    }
    .dropdown-menu li a:hover {
        background-color: red !important;
    }

    .jumbotron {
            background-color: #89D3D6;
            color: #fff;
            padding: 100px 25px;
            background-image: url("../img/jumbotron_bg.jpg");
            background-size: cover;
        }


    .container-fluid {
        padding: 5px 50px;
    }

    input[type=submit] {
        background-color: #0C666F;
        color: #EDEAE5;
        padding: 12px 20px;
        border: none;
        border-radius: 4px;
        cursor: pointer;
        float: right;
    }

    input[type=submit]:hover {
        background-color: #0C666F;
        color:#0C666F
    }


input[type=text], select, textarea{
    width: 100%;
    padding: 12px;
    border: 1px solid #ccc;
    border-radius: 4px;
    box-sizing: border-box;
    resize: vertical;
}

.panel {
     border: 1px solid #A2ECD7;
     border-radius:0 !important;
     transition: box-shadow 0.5s;
 }
 .panel:hover {
     box-shadow: 30px 0px 40px rgba(0,0,0, .2);
 }

 .panel-heading {
     color: #fff !important;
     background-color: #A2ECD7 !important;
     padding: 25px;
     border-bottom: 0px solid transparent;
     border-top-left-radius: 0px;
     border-top-right-radius: 0px;
     border-bottom-left-radius: 0px;
     border-bottom-right-radius: 0px;
 }

 .panel-footer {
     background-color: #EDEAE5 !important;
 }


label {
    padding: 12px 12px 12px 0;
    display: inline-block;
}

input[type=submit] {
    background-color: #0C666F;
    color: #EDEAE5;
    padding: 12px 20px;
    border: none;
    border-radius: 4px;
    cursor: pointer;
    float: right;
}

input[type=submit]:hover {
    background-color: #FFF8C9;
    color:#0C666F
}
.logo {
  color: #FAE086;
    font-size: 100px;
}

.container {
    border-radius: 5px;
    background-color: #f2f2f2;
    padding: 20px;
}

.col-25 {
    float: left;
    width: 25%;
    margin-top: 6px;
}

.col-75 {
    float: left;
    width: 75%;
    margin-top: 6px;
}

/* Clear floats after the columns */
.row:after {
    content: "";
    display: table;
    clear: both;
}

footer {
    background-color: #2d2d30;
    color: #f5f5f5;
    padding: 32px;
    position: fixed;
    left: 0;
    right: 0;
    bottom: 0;
}


/* Responsive layout - when the screen is less than 600px wide, make the two columns stack on top of each other instead of next to each other */
@media (max-width: 600px) {
    .col-25, .col-75, input[type=submit] {
        width: 100%;
        margin-top: 0;
    }
}
</style>
<head>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
</head>
<body>


  <nav class="navbar navbar-inverse" class="collapse navbar-collapse">
    <div class="container-fluid">
      <div class="navbar-header">
        <div class="navbar-header">
          <a class="navbar-brand" href="{% url 'foodsupply:index' %}">K0</a>
        </div>
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
      </div>
      <div class="collapse navbar-collapse" id="myNavbar">
        <ul class="nav navbar-nav">
          <li><a href="{% url 'foodsupply:index' %}">Home</a></li>
        </ul>
        <ul class="nav navbar-nav navbar-right">
            <li class="dropdown"><a class="dropdown-toggle"  data-toggle="dropdown" href="#">Hub Manager<span class="caret"></span></a>
              <ul class="dropdown-menu">
                <li><a href="{% url 'foodsupply:household' %}">Household</a></li>
                <li><a href="{% url 'foodsupply:hub' %}">Hub Manager</a></li>
              </ul>
            </li>
        </ul>
      </div>
    </div>
</nav>

<div class="jumbotron text-center">
  <h1>Hub Manager</h1>
  <p>Resource Allocation Management</p>
</div>

<div id="about" class="container-fluid">
  <div class="row">
    <div class="col-sm-8">
      <h1 style="color:#14666E">Reporting and Analytics</h1>
      <h4>Get best advice on reallocation of resources using Machine Learning Optimization functions.</h4>
      <h6>As Hub Managers, this page gives you status updates on your hub.</h6>
    </div>
    <div class="col-sm-4">
    </div>
  </div>
</div>


<br>
<div id="pricing" class="container-fluid">
  </div>
    <div class="col-md-4 col-xs-12">
      <div class="panel panel-default text-center">
        <div class="panel-heading">
          <h1 style="color:#0C666F">Hub 1</h1>
        </div>
        <div class="panel-body">
          <p><strong>{{hub_1.house_count}}</strong> Total Households</p>
          <p><strong>{{hub_1.population}}</strong> Total Population</p>
          <p><strong>{{hub_1.days_to_exhaustion}}</strong> Days to Exhaustion</p>
          <p><strong>{{hub_1.critical_score}}</strong> Critical Score</p>
        </div>
        <div class="panel-footer">
          <a href="{% url 'foodsupply:report1' %}"
              style="text-decoration:none;color:white;">
              <h4 style="color:#0C666F">View</h4>
          </a>
        </div>
      </div>
    </div>
    <div class="col-md-4 col-xs-12">
      <div class="panel panel-default text-center">
        <div class="panel-heading">
          <h1 style="color:#0C666F">Hub 2</h1>
        </div>
        <div class="panel-body">
          <p><strong>{{hub_2.house_count}}</strong> Total Households</p>
          <p><strong>{{hub_2.population}}</strong> Total Population</p>
          <p><strong>{{hub_2.days_to_exhaustion}}</strong> Days to Exhaustion</p>
          <p><strong>{{hub_2.critical_score}}</strong> Critical Score</p>
        </div>
        <div class="panel-footer">
          <a href="{% url 'foodsupply:report2' %}"
              style="text-decoration:none;color:white;">
              <h4 style="color:#0C666F">View</h4>
          </a>
        </div>
      </div>
    </div>
    <div class="col-md-4 col-xs-12">
      <div class="panel panel-default text-center">
        <div class="panel-heading">
          <h1 style="color:#0C666F">Hub 3</h1>
        </div>
        <div class="panel-body">
          <p><strong>{{hub_3.house_count}}</strong> Total Households</p>
          <p><strong>{{hub_3.population}}</strong> Total Population</p>
          <p><strong>{{hub_3.days_to_exhaustion}}</strong> Days to Exhaustion</p>
          <p><strong>{{hub_3.critical_score}}</strong> Critical Score</p>
        </div>
        <div class="panel-footer">
          <a href="{% url 'foodsupply:report3' %}"
              style="text-decoration:none;color:white;">
              <h4 style="color:#0C666F">View</h4>
          </a>
        </div>
      </div>
    </div>
  </div>


  <form action="{% url 'foodsupply:optimization' %}" method="post"> {% csrf_token %}
    <div class="col-md-6 col-md-offset-3">
        <input action="{% url 'foodsupply:optimization' %}" type="submit" class="btn btn-primary btn-lg btn-block" value="Optmize">
    </div>
  </form>
<br>

</body>
</html>

katrina/foodsupply/templates/foodsupply/thankyou.html
<h1>Thank you</h1>

katrina/foodsupply/templates/foodsupply/view_household.html
<table>
    <thead>
        <tr>
            <th>hub_id</th>
            <th>population</th>

            <th>current_storage</th>
        </tr>
    </thead>
    <tbody>
        {% for hub in all_hub %}
            <tr><td>{{ hub.hub_id }}</td><td>{{ hub.current_storage }}</td><td>{{ hub.population }}</td></tr>
        {% endfor %}
    </tbody>
</table>